### ISSUE TITLE
Upgrade semver to 7.1.2 (nodejs)

### ISSUE THREAD

**Issue by troley** [eveoh/room-display#47]
## Summary

**Dependency to upgrade:** semver

**Target version:** 7.1.2 or later

**Reason:** no specific

## Additional information

This is a major upgrade. Shouldn't have any side effects based on the change log, though they mention that they drop support "very old node versions" since semver version 7.0.0,

## Change log

https://github.com/npm/node-semver/blob/master/CHANGELOG.md

## Acceptance criteria

- [ ] The dependency has been upgraded.

**Comment by MikeN123** [comment]
It seems that after the changes in #54 we no longer depend on semver directly, so we can close this ticket.
