### ISSUE TITLE
Upgrade Gradle to v6

### ISSUE THREAD

**Issue by troley** [eveoh/room-display#52]
## Summary

**Dependency to upgrade:** Gradle

**Target version:** 6.x or later

**Reason:** no specific

## Additional information

The `gradle-node-plugin` depdendency also requires attention after this upgrade, because it breaks as soon as Gradle is upgraded to version 6+.

Relevant issue: https://github.com/srs/gradle-node-plugin/issues/351
Relevant depedency which seems to be a drop-in replacement for the old dependency probably fixing the `gradle-node-plugin` issue: https://github.com/node-gradle/gradle-node-plugin

## Change log

https://docs.gradle.org/6.0/release-notes.html

## Acceptance criteria

- [ ] The dependency has been upgraded.

**Comment by MikeN123** [comment]
We're dropping Gradle from room-display, so we can close this ticket.
